source 'https://rubygems.org'

gem 'rails', '4.1.4'
gem 'sqlite3'
# gem 'sass-rails', '~> 4.0.3'
# gem 'uglifier', '>= 1.3.0'
# gem 'coffee-rails', '~> 4.0.0'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer',  platforms: :ruby

# gem 'jquery-rails'
# gem 'turbolinks'
# gem 'jbuilder', '~> 2.0'

gem 'dotenv'
gem 'dotenv-rails'
gem 'email_validator'

# group :doc do
#   gem 'sdoc', require: false
# end

group :development, :test do
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'guard-rspec'
  gem 'powder', require: false if `uname` =~ /Darwin/
  gem 'rb-fsevent' if `uname` =~ /Darwin/
  gem 'rspec-rails', '~> 3.0.0'
  gem 'shoulda-matchers'
  gem 'spring'
  gem 'spring-commands-rspec'
end

group :production do
  gem 'unicorn'
end
